/* Gen II — Johto. Carries forward the 22 Major Arcana but recast with Gen II
   Pokémon. The spread expands to 5 positions on a day/night cycle, each card
   gains a shadow voice (the "yet/still" counterpoint), and the synthesis adds
   a type-balance reading. */
import type { Card, Position } from "../data/cards";
import type { Universe } from "./types";

const POSITIONS_GEN2: Position[] = [
  { key: "dawn", label: "Dawn", sub: "the root", line: "Where this began" },
  { key: "day", label: "Day", sub: "the waking life", line: "Where you stand now" },
  { key: "dusk", label: "Dusk", sub: "the challenge", line: "What stands across the path" },
  { key: "night", label: "Night", sub: "the hidden", line: "What works beneath" },
  { key: "star", label: "Star", sub: "the guidance", line: "What steers you onward" },
];

const DECK_GEN2: Card[] = [
  {
    n: 0,
    roman: "0",
    arcana: "The Fool",
    mon: "Togepi",
    dex: 175,
    types: ["Normal"],
    up: "From the egg, naked of doubt. Togepi greets every face as a kindness and every horizon as a friend; it cannot yet imagine harm. Beneath that soft shell sleeps a brightness it has not learned to fear. Begin the way the small thing begins — without armor, and without question.",
    upShadow: "…yet a world unguarded is also a world unwarned. Carry the openness, but learn the shape of teeth.",
    upKeys: ["Wonder", "Trust", "First light"],
    rev: "The shell tightens. What once met the world face-first now flinches from it; the joy curdles into wariness too soon. To stay forever in the egg is to never hatch, and what cannot hatch cannot share its light.",
    revShadow: "…even so, the small fear has a reason. Honor it once, then set it down.",
    revKeys: ["Withdrawn", "Premature caution", "Unhatched"],
  },
  {
    n: 1,
    roman: "I",
    arcana: "The Magician",
    mon: "Xatu",
    dex: 178,
    types: ["Psychic", "Flying"],
    up: "Two-faced and unmoving, Xatu watches yesterday and tomorrow at once. It does not strive — it stands, and the world moves through it. The hand that reaches out is the hand the hand was always going to be. Channel; do not wish.",
    upShadow: "…yet stillness can become statue. Will makes; it does not contain. Move when the totem stirs.",
    upKeys: ["Manifestation", "Stillness", "Channel"],
    rev: "The totem stares at nothing. Power held too still curdles into spectacle; the gaze that once saw past and future now only watches itself. Brilliance without aim is just an unmoving body in costume.",
    revShadow: "…still, even a fixed gaze sees. Begin where the eyes are already pointed.",
    revKeys: ["Spectacle", "Inertia", "Unmoving will"],
  },
  {
    n: 2,
    roman: "II",
    arcana: "The High Priestess",
    mon: "Lugia",
    dex: 249,
    types: ["Psychic", "Flying"],
    up: "Beneath miles of silver water, Lugia keeps the storm that would otherwise eat the coast. What it knows it does not say; what it says, the sea remembers. Listen for the answer below the answer — the truth lives in the silt.",
    upShadow: "…but the deep can drown the asker. Do not dive farther than your breath.",
    upKeys: ["The depths", "Knowing", "Held storm"],
    rev: "The waters churn. What was kept now leaks; what was felt is denied. The storm the Priestess once held seeks its own shore, and the small voice within is shouted over by the surf.",
    revShadow: "…still, the small voice is the true one. Lower the noise; the depth is patient.",
    revKeys: ["Unstilled", "Denied knowing", "Surfacing storm"],
  },
  {
    n: 3,
    roman: "III",
    arcana: "The Empress",
    mon: "Miltank",
    dex: 241,
    types: ["Normal"],
    up: "From Miltank's body, milk enough for whoever wanders by. She does not ask if you have earned the cup — only whether the cup is empty. Abundance, given without a ledger, finds its way back as more abundance. Tend; you are already a hearth.",
    upShadow: "…even hearths consume what feeds them. Pour, but pour from the spring, not the cup.",
    upKeys: ["Abundance", "Nourishment", "Open hand"],
    rev: "The pail is empty and still she pours. What was love becomes obligation, what was milk becomes water, what was warmth becomes a slow leak. The mother who never rests is the mother who runs dry.",
    revShadow: "…yet a refilling spring is also a refusal to die. Sit, and let the well rise.",
    revKeys: ["Depletion", "Obligation", "Dry hearth"],
  },
  {
    n: 4,
    roman: "IV",
    arcana: "The Emperor",
    mon: "Steelix",
    dex: 208,
    types: ["Steel", "Ground"],
    up: "Forged under mountains, Steelix is law made of iron and pressure. Its body is a hallway; what travels through it is shaped by the walls. To command is not to shout but to make a corridor the world walks down. Stand; the law will follow.",
    upShadow: "…yet iron does not bend, and what does not bend cracks. Be the spine, not the bars.",
    upKeys: ["Command", "Iron spine", "Structure"],
    rev: "The corridor narrows until nothing passes. Authority hardens into rigidity, and the iron that was once shelter becomes a cage of its own making. The throne that fears motion will be inherited by stillness.",
    revShadow: "…still, the iron remembers what it shielded. Loosen one bolt, and the room breathes.",
    revKeys: ["Rigidity", "Iron cage", "Suffocating order"],
  },
  {
    n: 5,
    roman: "V",
    arcana: "The Hierophant",
    mon: "Slowking",
    dex: 199,
    types: ["Water", "Psychic"],
    up: "Crowned by the Shellder it cannot remove, Slowking is wisdom that arrived without being asked for. It speaks slowly because it is unhurried; it teaches the old way because the old way still works. Sit at the feet of what has lasted; you will be older when you stand.",
    upShadow: "…yet wisdom worn too long becomes weight. Even crowns deserve a holiday.",
    upKeys: ["Wisdom", "Tradition", "The crown"],
    rev: "The crown stiffens; the lesson loops. What was once teaching becomes performance — the same parable told to the wrong question. To revere a teacher is one thing; to be his echo is another.",
    revShadow: "…still, even a stale crown was earned. Honor the source, then revise the verse.",
    revKeys: ["Dogma", "Inherited script", "Stale crown"],
  },
  {
    n: 6,
    roman: "VI",
    arcana: "The Lovers",
    mon: "Espeon",
    dex: 196,
    types: ["Psychic"],
    up: "Espeon evolves not from training but from trust — sunlight on a bond strong enough to change the body. The choice was made long before the form arrived. Find the daylight your truer self requires, and walk toward it without explanation.",
    upShadow: "…yet a bond that demands the sun forgets the moon. Love both halves of who you've become.",
    upKeys: ["Bond", "Harmony", "Chosen path"],
    rev: "The fur loses its shine. What was alignment dulls to performance; what was sunlight becomes a held breath. The bond is asked to prove itself, and bonds that must prove themselves quietly stop.",
    revShadow: "…even so, what frayed is not gone. Speak once, kindly; the gem may yet warm.",
    revKeys: ["Misalignment", "Lost trust", "Daylight withheld"],
  },
  {
    n: 7,
    roman: "VII",
    arcana: "The Chariot",
    mon: "Donphan",
    dex: 232,
    types: ["Ground"],
    up: "Donphan curls into a wheel and the hill becomes a slope. There is no second-guessing inside the spin — only the line and the speed. To win this way is not to overpower the world but to commit to one direction with the whole body. Pick the lane; do not hesitate to fill it.",
    upShadow: "…yet a wheel does not steer. Look up before you start to roll.",
    upKeys: ["Charge", "Momentum", "Earth-drive"],
    rev: "The roll wobbles; the line bends. Speed without aim is just an accident in motion, and the same tusks that broke the wall now break the floor. Brake; reset your feet before you set them spinning again.",
    revShadow: "…still, the wheel remembers how to roll. Begin again, but level the ground first.",
    revKeys: ["Stalled charge", "Misaimed drive", "Spent momentum"],
  },
  {
    n: 8,
    roman: "VIII",
    arcana: "Strength",
    mon: "Heracross",
    dex: 214,
    types: ["Bug", "Fighting"],
    up: "Heracross can lift a tree it did not plant — and chooses where to set it down. The horn is single because the purpose is single; the force is great because the grip is exact. To be strong is to know what not to crush.",
    upShadow: "…yet the kindest strength can still tire. Set down what you need not carry.",
    upKeys: ["Restraint", "Lifted weight", "Quiet might"],
    rev: "The horn jabs at every problem. Strength that forgets its softness becomes a weapon that wears out its wielder; the back that lifted everything finds itself unable to stand. Power without rest is power eating itself.",
    revShadow: "…even so, the body knows the work it loves. Rest, and the strength returns kinder.",
    revKeys: ["Brute force", "Overlifted", "Strain"],
  },
  {
    n: 9,
    roman: "IX",
    arcana: "The Hermit",
    mon: "Ampharos",
    dex: 181,
    types: ["Electric"],
    up: "From the lighthouse on the cliff, Ampharos burns alone so that the ships can find each other. It does not seek company — the work is the company. There is a kind of light that only the unaccompanied can hold. Climb the tower; the dark needs you up there.",
    upShadow: "…yet a lighthouse is not a hermitage. Come down at dawn; eat with people.",
    upKeys: ["The lantern", "Solitary light", "Beacon"],
    rev: "The bulb flickers; the keeper sleeps in the lamp room. Solitude curdles into self-erasure when no ship is allowed to find the shore. The light that no one ever sees becomes a light that forgets it shines.",
    revShadow: "…still, even a tired beacon is a beacon. Open one window. The first ship will do the rest.",
    revKeys: ["Isolation", "Dimmed beacon", "Withdrawn light"],
  },
  {
    n: 10,
    roman: "X",
    arcana: "Wheel of Fortune",
    mon: "Unown",
    dex: 201,
    types: ["Psychic"],
    up: "Twenty-six small shapes drift through the ruined halls, and any sentence is possible. What appears as accident is the wheel laying down a letter; what appears as meaning is the next letter falling. Read what arrives. Do not insist on the next word.",
    upShadow: "…yet a wheel that turns alone teaches nothing. Be the reader, not the page.",
    upKeys: ["Turning symbols", "Synchronicity", "Fated alphabet"],
    rev: "The letters jumble. What was the slow accrual of meaning fragments into noise; what was rhythm becomes static. The ruin asks the wrong question, and the answer arrives in scrambled glyphs.",
    revShadow: "…even noise has a key. Listen for the repeated symbol; that is where the wheel still turns.",
    revKeys: ["Stalled wheel", "Pattern broken", "Misread sign"],
  },
  {
    n: 11,
    roman: "XI",
    arcana: "Justice",
    mon: "Skarmory",
    dex: 227,
    types: ["Steel", "Flying"],
    up: "Skarmory's wings are folded steel — every feather a single fact. It flies not by struggling but by being heavy in exactly the right places. Cut clean; the world will respect the cut. There is no Justice that hides the math.",
    upShadow: "…yet a blade that loves its edge will find a use for it. Justice is not vengeance dressed nicely.",
    upKeys: ["The blade", "Honest weight", "Consequence"],
    rev: "The wing falters; a feather rusts. What was honesty leans, and the cut goes crooked; the weight that should have settled the matter instead tilts it further. A balance fudged is a balance broken.",
    revShadow: "…even a bent blade can be straightened. Begin with the smaller lie.",
    revKeys: ["Dishonest scale", "Bent blade", "Suppressed truth"],
  },
  {
    n: 12,
    roman: "XII",
    arcana: "The Hanged One",
    mon: "Sudowoodo",
    dex: 185,
    types: ["Rock"],
    up: "Sudowoodo holds the pose of a tree until the rain comes; then it steps out of the lie at last. The waiting is not failure — it is the time the truth requires. Hang where the world has put you; you will see the underside, which the upright never could.",
    upShadow: "…yet a tree that never moves is still a thing pretending. Step when the rain comes.",
    upKeys: ["Stillness", "Surrender", "Inverted view"],
    rev: "The pose holds past its purpose. What was patience becomes a refusal to be seen; what was waiting becomes a quiet collapse standing up. The rain came and was waved off, and the masquerade hardens into the mask.",
    revShadow: "…still, even fossilized stillness can crack. One honest sigh is the first chip.",
    revKeys: ["Stalling", "Stuck pose", "Refused descent"],
  },
  {
    n: 13,
    roman: "XIII",
    arcana: "Death",
    mon: "Houndoom",
    dex: 229,
    types: ["Dark", "Fire"],
    up: "Houndoom waits at the edge of the field where the day ends. It does not chase what has run its course; it simply names it finished. To end well is to let the hound have its bone — the next morning needs the room. Let the door close; the next door will know how.",
    upShadow: "…yet a hound that bays at every shadow burns its own throat. Some endings can wait.",
    upKeys: ["Threshold", "Ending fire", "The hound at the door"],
    rev: "The fire smolders without combusting. What needed to end is given more rooms to occupy; what asked to be released is asked again to stay. The hound paces at the threshold, denied its work.",
    revShadow: "…even so, a slow release is still a release. Loosen one finger, then the next.",
    revKeys: ["Refused ending", "Lingering", "Smoke without release"],
  },
  {
    n: 14,
    roman: "XIV",
    arcana: "Temperance",
    mon: "Suicune",
    dex: 245,
    types: ["Water"],
    up: "Suicune walks the pond from the lake from the river from the sea, and what it touches forgets it was ever fouled. The pour is not hurried because the source is not anxious. To temper is to mix two truths in such proportion that both survive. Pour slowly; the river always arrives.",
    upShadow: "…yet even pure water can drown the unready. Test the temperature; then offer the cup.",
    upKeys: ["Clean current", "Pouring", "Pure measure"],
    rev: "The current churns silt. What was harmony becomes correction; what was measure becomes excess. The pour goes on past the cup's brim, and the floor of the room learns the taste of what was meant for the throat.",
    revShadow: "…still, the river knows how to find its level. Stop pouring; the cup remembers its shape.",
    revKeys: ["Imbalance", "Over-pour", "Disturbed water"],
  },
  {
    n: 15,
    roman: "XV",
    arcana: "The Devil",
    mon: "Tyranitar",
    dex: 248,
    types: ["Rock", "Dark"],
    up: "Tyranitar walks and the weather changes — sand churns, mountains complain. The hunger is large and the chain is short; what it wants it has not yet learned to refuse. The Devil is not a stranger; it is the version of you that always wins the argument with the version that wanted to be good.",
    upShadow: "…yet a tyrant exhausted is a tyrant approachable. Wait out the storm; ask once it has tired.",
    upKeys: ["Wrath", "Sandstorm", "Chained appetite"],
    rev: "The sandstorm thins; the chain slackens. What held you held you because you would not look at it; in the moment you look, the weight is lighter than you feared. The mountain stops complaining, and the path forward is dusty but clear.",
    revShadow: "…even freed, the hunger leaves footprints. Walk the path slowly; do not invite the storm back to test it.",
    revKeys: ["Broken chain", "Released hunger", "Quiet after storm"],
  },
  {
    n: 16,
    roman: "XVI",
    arcana: "The Tower",
    mon: "Raikou",
    dex: 243,
    types: ["Electric"],
    up: "Raikou was made the night the Brass Tower burned — Ho-Oh's lightning shaped grief into a body. The strike does not warn; it reveals. What stood is gone, and what stood was already gone the moment the spark left the cloud. Move quickly; the next strike will be later.",
    upShadow: "…yet lightning lit, the path is visible. Look at what is now uncovered.",
    upKeys: ["Lightning", "Sudden disclosure", "Born of ruin"],
    rev: "The cloud thickens but the bolt does not fall. The tower stands because it has not yet been honest about its cracks; the air is heavy with the storm not yet permitted to break. To delay the strike is to make it larger.",
    revShadow: "…still, the held storm is not gone — only paused. Use the pause to lower the people from the upper floors.",
    revKeys: ["Averted strike", "Brittle tower", "Postponed reckoning"],
  },
  {
    n: 17,
    roman: "XVII",
    arcana: "The Star",
    mon: "Celebi",
    dex: 251,
    types: ["Psychic", "Grass"],
    up: "Celebi steps between the years as easily as between branches. Where the harm settled, the leaves return; where the despair settled, a child laughs. Hope is not a feeling — it is a thing the forest does each spring whether or not anyone watches. Believe quietly; the wood is already on its way back.",
    upShadow: "…yet hope without hands is decoration. Plant something today.",
    upKeys: ["Renewal", "Forest hope", "Time mended"],
    rev: "The shrine goes quiet. The forest does not stop renewing — only stops being witnessed; the timeline closes a small door, and what could have come through it must wait for another season. Despair is the forgetting that spring is a habit.",
    revShadow: "…still, the next spring is already approaching the door. Leave the latch undone.",
    revKeys: ["Despair", "Dimmed shrine", "Hope deferred"],
  },
  {
    n: 18,
    roman: "XVIII",
    arcana: "The Moon",
    mon: "Umbreon",
    dex: 197,
    types: ["Dark"],
    up: "Umbreon's gold rings glow when no one is looking. The moonlight does not show — it suggests, and what it suggests is closer to the truth than the daylit version. Walk the path at night; the daytime did not tell you everything. The dark knows.",
    upShadow: "…yet even moonlight throws shadows that lie. Trust the dream; test it at dawn.",
    upKeys: ["Veiled truth", "Night sense", "Dream knowing"],
    rev: "The rings dim, the gold steadies. What looked like mystery turns out to have been a misread surface; what felt like fate turns out to have been a held breath. The reveal is gentle, but it is a reveal.",
    revShadow: "…still, not every veil was hiding harm. Some were keeping warmth.",
    revKeys: ["Illusion seen through", "Cleared dream", "Veil lifted"],
  },
  {
    n: 19,
    roman: "XIX",
    arcana: "The Sun",
    mon: "Ho-Oh",
    dex: 250,
    types: ["Fire", "Flying"],
    up: "Ho-Oh's seven-colored flight is not flight — it is an arrival. Whatever it passes over is blessed without being asked, and whatever it leaves remembers the light for a season. Stand where the rainbow lands; you do not need to deserve the warmth.",
    upShadow: "…yet a blessing one keeps becomes an idol. Pass the light along before it dims.",
    upKeys: ["Radiance", "Blessing", "Rainbow"],
    rev: "The colors thin to a half-sky. What was the full pour of joy becomes a careful spoon of it; what would have been triumph is filed under 'enough for now.' The rainbow appears in someone else's window.",
    revShadow: "…still, half a rainbow is the start of the whole one. Tilt your head; the rest is closer than it looks.",
    revKeys: ["Dimmed light", "Withheld blessing", "Borrowed dawn"],
  },
  {
    n: 20,
    roman: "XX",
    arcana: "Judgement",
    mon: "Entei",
    dex: 244,
    types: ["Fire"],
    up: "Entei is the body that the dead Pokémon was given; the volcano did not waste the life. The trumpet does not invite you — it informs you that the morning is already underway. Rise; what called you cannot be unheard.",
    upShadow: "…yet not every wakening is gentle. Drink water before you run.",
    upKeys: ["Awakening", "Volcanic rebirth", "The horn calls"],
    rev: "The horn sounds; the room turns over. What is called is asked to wait, what is risen is asked to lie back down; the morning happens elsewhere while one body insists on dusk. The reckoning is not avoided — only postponed.",
    revShadow: "…still, the horn does not tire. Tomorrow it will sound again.",
    revKeys: ["Refused call", "Unfinished reckoning", "Echoed horn"],
  },
  {
    n: 21,
    roman: "XXI",
    arcana: "The World",
    mon: "Crobat",
    dex: 169,
    types: ["Poison", "Flying"],
    up: "Crobat is what Zubat becomes when the bond is whole; the two wings grow two more, the flight becomes silent, the line is closed. There is no more to evolve into because there is no more that the evolution was for. Stand in the circle; the work has done you.",
    upShadow: "…yet wholeness is not stillness. The wings still beat; the world still turns.",
    upKeys: ["Completion", "Bond fulfilled", "The four wings"],
    rev: "The fourth wing does not arrive. What was almost finished asks to be finished, and the asking is a kind of finishing in itself — but the line stays open. Close the door you can close; the rest of the circle will find its shape.",
    revShadow: "…still, an open circle is a wider circle. Some endings are best left as doors.",
    revKeys: ["Incompletion", "Unclosed circle", "Loose flight"],
  },
];

export const GEN2: Universe = {
  id: "gen2",
  label: "Gen II",
  tagline: "Johto · Day & Night",
  deck: DECK_GEN2,
  positions: POSITIONS_GEN2,
  spreadShape: "cross",
  hasShadowVoice: true,
  hasTypeBalance: true,
};
