/* Vendor the official-artwork sprites for the deck's Pokemon into public/mons/.
   The dex list is derived from src/data/cards.ts so it stays in sync with the
   deck. Re-run with `node scripts/fetch-sprites.mjs` after adding cards.

   Source: PokeAPI/sprites (https://github.com/PokeAPI/sprites) — official
   artwork PNGs (transparent background), which we render as type-tinted
   silhouettes via CSS mask in the Sigil component. */
import { readFileSync, readdirSync, mkdirSync, writeFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

// Scan every universe deck (src/universes/gen*.ts) plus the original cards.ts
// so adding a new generation just means adding its file, not editing this script.
const sources = [
  join(root, "src/data/cards.ts"),
  ...readdirSync(join(root, "src/universes"))
    .filter((f) => f.endsWith(".ts") && f !== "types.ts" && f !== "index.ts")
    .map((f) => join(root, "src/universes", f)),
];
const dexes = sources.flatMap((p) =>
  [...readFileSync(p, "utf8").matchAll(/\bdex:\s*(\d+)/g)].map((m) => Number(m[1])),
);
const unique = [...new Set(dexes)].sort((a, b) => a - b);
console.log(`Decks have ${unique.length} unique dex numbers:`, unique.join(", "));

const outDir = join(root, "public/mons");
mkdirSync(outDir, { recursive: true });

const base =
  "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork";

let ok = 0;
let failed = [];
for (const dex of unique) {
  const out = join(outDir, `${dex}.png`);
  if (existsSync(out)) {
    ok++;
    continue;
  }
  try {
    const res = await fetch(`${base}/${dex}.png`);
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    const buf = Buffer.from(await res.arrayBuffer());
    writeFileSync(out, buf);
    console.log(`  ✓ ${dex}.png (${(buf.length / 1024).toFixed(0)} KB)`);
    ok++;
  } catch (e) {
    console.warn(`  ✗ ${dex}.png — ${e.message}`);
    failed.push(dex);
  }
}
console.log(`\nDone: ${ok}/${unique.length} sprites in public/mons/`);
if (failed.length) console.log("Missing:", failed.join(", "));

// emit a manifest so the Sigil component knows which dexes have a vendored
// sprite (and can fall back to the type glyph for any that don't).
const have = unique.filter((d) => !failed.includes(d));
const manifest =
  `// AUTO-GENERATED by scripts/fetch-sprites.mjs — do not edit by hand.\n` +
  `// Dex numbers with a vendored sprite in public/mons/.\n` +
  `export const SPRITE_DEXES: ReadonlySet<number> = new Set([${have.join(", ")}]);\n`;
writeFileSync(join(root, "src/data/sprites.ts"), manifest);
console.log(`Wrote manifest src/data/sprites.ts (${have.length} dexes).`);
