// AUTO-GENERATED by scripts/fetch-sprites.mjs — do not edit by hand.
// Dex numbers with a vendored sprite in public/mons/.
export const SPRITE_DEXES: ReadonlySet<number> = new Set([32, 34, 35, 54, 65, 68, 78, 79, 94, 97, 104, 113, 123, 129, 130, 131, 144, 145, 146, 150, 151, 169, 175, 178, 181, 185, 196, 197, 199, 201, 208, 214, 227, 229, 232, 241, 243, 244, 245, 248, 249, 250, 251]);
